spring:
  rabbitmq:
    host: ${CLOUD_BUS_RABBIT_HOST}
    port: ${CLOUD_BUS_RABBIT_PORT}
    username: ${CLOUD_BUS_RABBIT_USERNAME}
    password: ${CLOUD_BUS_RABBIT_PASSWORD}


service-discovery:
  url: localhost
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${service-discovery.url}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${service-discovery.url}:${service-discovery.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"


example:
  first: first-1
  second: second-2
